services:
  payment:
      image: paymentimage:latest
      ports: 
        - "3005:3000"
      environment:
        - DATABASE_URL=${DB_URL}
        - KONNECT_API_URL=${KONNECT_API_URL}
        - KONNECT_API_KEY=${KONNECT_API_KEY}
        - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
        - NATS_SERVER=nats://nats:4222

      depends_on:
        - postgresql
      networks:
        - paymentnetwork
        - natsnetwork

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - paymentnetwork

networks:
  paymentnetwork:
    driver: bridge
  natsnetwork:
    external: true

volumes:
  postgres-data:
    driver: local
  nats-data:
    driver: local