FROM node:18.19.1
WORKDIR /payment/
RUN npm install -g @nestjs/cli && apt-get update && apt-get install -y curl sudo && apt-get install -y curl jq
COPY package*.json .
RUN ["npm","install"]
COPY . .
COPY start.sh ./
RUN chmod +x start.sh
RUN ["nest","build"]
CMD ["./start.sh"]
