apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: paymentapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentapp
  template:
    metadata:
      labels:
        app: paymentapp
    spec:
      containers:
      - name: paymentapp-container
        image: rawaakr1/paymentimage:latest
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: db-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: db-password
        - name: DATABASE_NAME
          value: "Payments"
        - name: POSTGRES_HOST
          value: "postgresql-service2"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(DATABASE_NAME)"
        - name: KONNECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: KONNECT_API_KEY
        - name: NGROK_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: NGROK_AUTH_TOKEN
        - name: KONNECT_API_URL
          valueFrom:
            configMapKeyRef:
              name: payment-config
              key: KONNECT_API_URL
        - name: WEBHOOK_URL
          value: "http://192.168.58.2:30210/payment/webhook"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels: S
    app: paymentapp
spec : 
  type: NodePort
  selector:
    app: paymentapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30210