apiVersion : v1
kind : Secret
metadata :
  name : payment-secret
type : Opaque
data: 
  db-username: cG9zdGdyZXM=  
  db-password: UmsyMjEw       
  KONNECT_API_KEY : NjZhMzZlNDJmMjUxNWQwZDM3N2UwZTY5OkFRRkkzWGE1R3BwY3R0Y3RBaVVIbHVDNlYyNg==
  NGROK_AUTH_TOKEN : MmtLM1YySVFwd2RqNUR6cUZJZ3lSbURzQ25xXzIzN3ZNcUtRWEVMWVJjeThTRk1xOQ==