services:
  app:
    image: authimage:latest
    ports: 
      - "3001:3000"
    environment:
      - DATABASE_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgresql
    networks:
      - mynetwork

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
    driver: local
