FROM node:18.19.1
WORKDIR /auth/
COPY common ./common
WORKDIR /auth/authentication
COPY authentication/package*.json ./
RUN ["npm","install"]
COPY authentication/. ./
RUN npm run build && \
    npx prisma migrate && \
    npx prisma generate && \
    npm install -g @nestjs/cli

CMD ["node", "./dist/authentication/src/main.js"]
